### PR TITLE
Implement GitHub Actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Differences to previous CI (Travis):
* not using `set -e/+e`
* using stock `rebar3` instead of installing latest (don't know if this is a hard requirement)
* not implementing `if [[ "$TRAVIS_OTP_RELEASE" = '20.2' ]] && [[ "$TRAVIS_EVENT_TYPE" = 'cron' ]]; then make update; fi` since no 20.2 was configured (which means this wasn't running, recently)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Hi. Is this OK for merging? Do you want further changes?

**Comment by paulo-ferraz-oliveira** [comment]
Ping.

**Comment by benoitc** [comment]
sorry I have been sidetracked. I have like on hackney created an empty action file. Let me know if you want to do the merge. Otherwise I can probably do it later today.

**Comment by paulo-ferraz-oliveira** [comment]
I can rebase and test it before the merge, no prob. It's safer this way.

**Comment by paulo-ferraz-oliveira** [comment]
Failing. Happy about the previous decision to rebase. Let me check what's happening.

**Comment by benoitc** [comment]
> Failing. Happy about the previous decision to rebase. Let me check what's happening.

it seems to run the last part of the action outside of the repository... not sure why though

**Comment by paulo-ferraz-oliveira** [comment]
All GitHub Actions [tests are passing](https://github.com/certifi/erlang-certifi/actions/runs/470283595).

**Comment by paulo-ferraz-oliveira** [comment]
> > Failing. Happy about the previous decision to rebase. Let me check what's happening.
> 
> Thanks! it seems to run the last part of the action outside of the repository... not sure why though

Well, what happens is that `actions/checkout@v2` only pulls stuff as a Git repo from 2.18 (which is not in some containers by default - which is the reason I added the install procedure). From then on it seems straightforward.

**Comment by benoitc** [comment]
thanks for the changes!

**Pull request merged**
